#!/bin/bash
DNAME=`dirname $0`
BSPWMD=$HOME/.config/bspwm/
SXHKD=$HOME/.config/sxhkd/
SCRIPTD=$HOME/.config/scripts/

mkdirs() {
	mkdir -p $BSPWMD
	mkdir -p $SXHKD
	mkdir -p $SCRIPTD
}

clean() {
	cd $DNAME
	rm -rf package-query yaourt bspwm-git sxhkd-git sres-git dmenu2-hg
	rm *.tar.gz
}

inst_needed() {
	wget https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz
	wget https://aur.archlinux.org/packages/bs/bspwm-git/bspwm-git.tar.gz
	wget https://aur.archlinux.org/packages/sx/sxhkd-git/sxhkd-git.tar.gz
	wget https://aur.archlinux.org/packages/sr/sres-git/sres-git.tar.gz
	wget https://aur.archlinux.org/packages/dm/dmenu2-hg/dmenu2-hg.tar.gz
	wget https://aur.archlinux.org/packages/ya/yaourt/yaourt.tar.gz
	wget https://aur.archlinux.org/packages/po/powerline-fonts-git/powerline-fonts-git.tar.gz
	wget https://aur.archlinux.org/packages/rx/rxvt-unicode-patched/rxvt-unicode-patched.tar.gz
	tar xf package-query.tar.gz
	tar xf yaourt.tar.gz
	tar xf bspwm-git.tar.gz
	tar xf sxhkd-git.tar.gz
	tar xf sres-git.tar.gz
	tar xf dmenu2-hg.tar.gz
	tar xf powerline-fonts-git.tar.gz
	tar xf rxvt-unicode-patched.tar.gz

	cd package-query
	makepkg -s
	sudo pacman -U *.pkg.tar.xz --noconfirm

	cd ../yaourt
	makepkg -s
	sudo pacman -U *.pkg.tar.xz --noconfirm

	cd ../bspwm-git
	makepkg -s
	sudo pacman -U *.pkg.tar.xz --noconfirm

	cd ../sxhkd-git
	makepkg -s
	sudo pacman -U *.pkg.tar.xz --noconfirm

	cd ../sres-git
	makepkg -s
	sudo pacman -U *.pkg.tar.xz --noconfirm

	cd ../dmenu2-hg
	makepkg -s
	sudo pacman -U *.pkg.tar.xz --noconfirm

	cd ../powerline-fonts-git
	makepkg -s
	sudo pacman -U *.pkg.tar.xz --noconfirm

	cd ../rxvt-unicode-patched
	makepkg -s
	sudo pacman -U *.pkg.tar.xz --noconfirm

	sudo pacman -S tlp iw ethtool acpi feh i3lock imagemagick dzen2 --noconfirm
	sudo systemctl enable tlp tlp-sleep
	sudo systemctl start tlp tlp-sleep

	clean
}

inst_scripts() {
	cp $DNAME/scripts/* $SCRIPTD
	if [ -f $HOME/.xinitrc ] ; then
		echo "Backing up your xinitrc to $HOME/.xinitrc.back"
		cp $HOME/.xinitrc $HOME/.xinitrc.back
	fi
	if [ -f $HOME/.Xresources ] ; then
		echo "Backing up your Xresources to $HOME/.Xresources.back"
		cp $HOME/.Xresources $HOME/.Xresources.back
	fi
	cp $DNAME/Xresources $HOME/.Xresources
	cp $DNAME/xinitrc $HOME/.xinitrc
}

inst_bspwm() {
	if [ ! -f $BSPWMD/bspwmrc ] ; then
		cp $DNAME/bspwm/bspwmrc-single $BSPWMD/bspwmrc
	fi
	if [ ! -d $BSPWMD/panel ] ; then
		cp -R $DNAME/bspwm/panel $BSPWMD
	fi
	if [ ! -f $SXHKD/sxhkdrc ] ; then
		cp $DNAME/bspwm/sxhkdrc $SXHKD
	fi
	cp -r $DNAME/scripts $SXHKD
}

case $1 in
	'--all')
		mkdirs
		inst_scripts
		inst_bspwm
		inst_needed
		;;
	'--deps')
		inst_needed
		;;
	'--clean')
		clean
		;;
esac
