#!/bin/bash
DNAME=$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)
BSPWMD=$HOME/.config/bspwm/
SXHKD=$HOME/.config/sxhkd/
SCRIPTD=$HOME/.config/scripts/
WMMD=$HOME/.config/wmm
GTK3=$HOME/.config/gtk-3.0
PKGS=(package-query yaourt bspwm-git sxhkd-git sres-git dmenu2 txtw-git xtitle-git powerline-fonts-git rxvt-unicode-patched urxvt-clipboard ttf-google-fonts-git)

mkdirs() {
	mkdir -p $BSPWMD
	mkdir -p $SXHKD
	mkdir -p $SCRIPTD
	mkdir -p $WMMD
	mkdir -p $GTK3
}

clean() {
	for i in ${PKGS[@]} ; do
		rm -rvf $DNAME/$i
		rm -v $DNAME/${i}.tar.gz
	done
}

inst_needed() {
	for  i in ${PKGS[@]} ; do
		cd $DNAME
		wget "https://aur.archlinux.org/packages/`echo $i | cut -c 1-2`/$i/${i}.tar.gz"
		tar xf $DNAME/${i}.tar.gz
		cd $DNAME/$i
		makepkg -s --noconfirm
		sudo pacman -U *.pkg.tar.xz --noconfirm
	done

	sudo pacman -S tlp scrot iw ethtool acpi feh i3lock imagemagick dzen2 \
		firefox firefox-i18n-en-us gnome-themes-standard adwaita-icon-theme --noconfirm
	sudo systemctl enable tlp tlp-sleep
	sudo systemctl start tlp tlp-sleep

	gem install wmm

	clean
}

inst_scripts() {
	cp $DNAME/scripts/* $SCRIPTD
	if [ -f $HOME/.xinitrc ] ; then
		echo "Backing up your xinitrc to $HOME/.xinitrc.back"
		cp $HOME/.xinitrc $HOME/.xinitrc.back
	fi
	if [ -f $HOME/.Xresources ] ; then
		echo "Backing up your Xresources to $HOME/.Xresources.back"
		cp $HOME/.Xresources $HOME/.Xresources.back
	fi
	cp $DNAME/Xresources $HOME/.Xresources
	cp $DNAME/xinitrc $HOME/.xinitrc
	cp $DNAME/gtk3-settings $GTK3/settings.ini
	cp $DNAME/gtkrc-2.0 $HOME/.gtkrc-2.0
}

inst_bspwm() {
	if [ ! -f $BSPWMD/bspwmrc ] ; then
		cp $DNAME/bspwm/bspwmrc $BSPWMD/bspwmrc
	fi
	if [ ! -d $BSPWMD/panel ] ; then
		cp -R $DNAME/bspwm/panel $BSPWMD
	fi
	if [ ! -f $SXHKD/sxhkdrc ] ; then
		cp $DNAME/bspwm/sxhkdrc $SXHKD
	fi
	cp -r $DNAME/scripts $SXHKD
	cp $DNAME/wmm.yml $WMMD
}

case $1 in
	'--all')
		mkdirs
		inst_scripts
		inst_bspwm
		inst_needed
		;;
	'--deps')
		inst_needed
		;;
	'--clean')
		clean
		;;
esac
