#! /bin/sh

bspc monitor -d I II III IV V

bspc config border_width        2
bspc config window_gap          5
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

$HOME/.config/bspwm/panel/panel dzen2 &
