#!/usr/bin/env bash
DIR=`dirname $0`
source $DIR/dmenu-config
cat ~/.dmenu-cache | dmenu -fn "$FONT:pixelsize=$FONT_SIZE" -i -l $DMENUL -w $DMENUW -h $DMENUH -x $DMENUXPOS -y $DMENUYPOS -nb $BG_COLOR -nf $FG_COLOR -sb $SBG_COLOR -sf $SFG_COLOR | xargs xdg-open &>/dev/null
