#!/bin/bash

DATE=$(date '+%F-%H:%M:%S')
IMG=$DATE.png

DIR=$HOME/Pictures

scrot $DIR/$IMG

if [ -e $NOTIFY_PIPE ] ; then
	rm $NOTIFY_PIPE
fi

echo "^ca(1, feh $DIR/$IMG)Screenshot taken $DIR/$IMG^ca()" > "$NOTIFY_PIPE"

notify
