#!/bin/bash

DIR=`dirname $0`
. $DIR/notify-config

DATE=$(date '+%F-%H:%M:%S')
IMG=$DATE.png

PDIR=$HOME/Pictures

scrot $PDIR/$IMG

if [ -e $NOTIFY_PIPE ] ; then
	rm $NOTIFY_PIPE
fi

echo "^ca(1, feh $PDIR/$IMG)Screenshot taken $PDIR/$IMG^ca()" > "$NOTIFY_PIPE"

notify
