#!/bin/bash
while [ true ]
do
	CUR_TIME=$(date +%T)
	if [[ $CUR_TIME > '20:00:00' ]] ; then
		redshift -l 41:87
	fi
	if [[ $CUR_TIME < '07:00:00' ]] ; then
		redshift -l 41:87
	fi
	if [[ $CUR_TIME > '07:00:00' ]] ; then
		if pgrep redshift &>/dev/null ; then
			pkill redshift
		fi
	fi
	sleep 10s
done
